domain:
  # domain http://localhost:8080//asyysy_core
  # https://www.asyysy.cn/asyysy_core
  domain: //huangyy.utools.club/
  short-url:
    domain: http://d.asyysy.cn
  tianqiapi_com:
    ncp_api_url : https://tianqiapi.com/api
    ncp_api_version: epidemic
    appid: 49174617
    appsecret: 24ZQu9p9
    ncp_data_timeout: 600
  wx:
    token: hyy210381
    appid: wxd5407394de781115
    appsecret: e6e9bb852143305efc8802716d762629
  qq:
    app_id: 101852685
    app_key: 0c157ca044b8f179fb167f3eb362faf3
    redirect_uri: http://yysy.wicp.net/asyysy_core/api/qq/callback
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    password: 123123112233
    url: jdbc:mysql://localhost:3306/asyysy_core?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    initialization-mode: never
    schema: classpath:database/style.sql
    data: classpath:database/data.sql
    continue-on-error: false
    sql-script-encoding: utf-8
    separator: ;

  redis:
    hostName: 127.0.0.1
    port: 6379
    timeout: 300
  thymeleaf:
    cache: false
